package pagg;

import java.awt.Color;
import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.ImageObserver;
import java.awt.image.ImageProducer;
import java.awt.image.MemoryImageSource;
import java.awt.image.PixelGrabber;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import sun.swing.ImageIconUIResource;

/**
 *
 * @author troublefox
 */
public class PAGGMainFrame extends javax.swing.JFrame {

    private FieldTableModel fieldTableModel;
    private int s1row;
    private int s1col;
    private int s2row;
    private int s2col;
    private List<Coordinates> sm = new ArrayList<>();
    /**
     * Creates new form PAGGMainFrame
     */
    public PAGGMainFrame() {
        
        fieldTableModel = new FieldTableModel();
//        ImageCellRenderer renderer = new ImageCellRenderer();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Start = new javax.swing.JButton();
        movementbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(fieldTableModel);
        for (int i = 0; i < 32; i++) {

            int colIndex = i;  // show image at (row 1, col 1)
            TableColumn col = jTable1.getColumnModel().getColumn(colIndex);
            ImageCellRenderer renderer = new ImageCellRenderer();
            col.setCellRenderer(renderer);

            setForeground(Color.BLUE);
            setBackground(Color.BLACK);

            //            col.setPreferredWidth(renderer.image.getWidth(null));
            col.setMaxWidth(32);
            jTable1.setRowHeight(32);
            //            jTable1.add(renderer.getLbl());

        }
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        Start.setText("Start");
        Start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StartMouseClicked(evt);
            }
        });

        movementbutton.setText("display movement");
        movementbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                movementbuttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(469, 469, 469)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Start)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(movementbutton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Start)
                    .addComponent(movementbutton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1034, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        
//        fieldTableModel.setValueAt(this, jTable1.getSelectedRow(), jTable1.getSelectedColumn());
        
//        if( (fieldTableModel.getTileTable()[jTable1.getSelectedRow()][jTable1.getSelectedColumn()].isWalkable() 
//         && !(fieldTableModel.getTileTable()[jTable1.getSelectedRow()][jTable1.getSelectedColumn()].isOccupied())) == true)
//        {
//            fieldTableModel.setValueAt(fieldTableModel.getPlayer1(), jTable1.getSelectedRow(), jTable1.getSelectedColumn());
////            System.out.println("von Zeile "+getS1row()+" und Spalte "+getS1col());
////            System.out.println("nach Zeile "+jTable1.getSelectedRow()+" und Spalte "+jTable1.getSelectedColumn());
////            System.out.println("originalTile: "+fieldTableModel.getTileTableOrigin()[getS1row()][getS1col()].getImage());
////            System.out.println("SpielfeldTile: "+fieldTableModel.getTileTable()[getS1row()][getS1col()].getImage());
////            fieldTableModel.setValueAt(fieldTableModel.getTileTableOrigin()[getS1row()][getS1col()], getS1row(), getS1col());
//            fieldTableModel.setValueAt(fieldTableModel.getTileTableOrigin()[fieldTableModel.getPlayer1().getRow()][fieldTableModel.getPlayer1().getCol()], fieldTableModel.getPlayer1().getRow(),fieldTableModel.getPlayer1().getCol());
//            fieldTableModel.getPlayer1().setRow(jTable1.getSelectedRow());
//            fieldTableModel.getPlayer1().setCol(jTable1.getSelectedColumn());
//            
//        }
//        else
//        {
////            System.out.println("Bewegung nicht möglich");
////            System.out.println("Zielort begehbar: "+fieldTableModel.getTileTable()[jTable1.getSelectedRow()][jTable1.getSelectedColumn()].isWalkable()
////            +";  besetzt: "+fieldTableModel.getTileTable()[jTable1.getSelectedRow()][jTable1.getSelectedColumn()].isOccupied());
//        }

        if( fieldTableModel.getTileTable()[jTable1.getSelectedRow()][jTable1.getSelectedColumn()].isPath() )
        {   
            for (Coordinates e : sm ) {
            System.out.println("x: "+e.getRow()+" y: "+e.getCol());
            fieldTableModel.getTileTable()[e.getRow()][e.getCol()].setPath(false);
            
            }
            fieldTableModel.setTileTable(fieldTableModel.getTileTableOrigin());
            
            
            fieldTableModel.setValueAt(fieldTableModel.getPlayer1(), jTable1.getSelectedRow(), jTable1.getSelectedColumn());
            fieldTableModel.setValueAt(fieldTableModel.getTileTableOrigin()[getS1row()][getS1col()], getS1row(), getS1col());
            fieldTableModel.setValueAt(fieldTableModel.getTileTableOrigin()[fieldTableModel.getPlayer1().getRow()][fieldTableModel.getPlayer1().getCol()], fieldTableModel.getPlayer1().getRow(),fieldTableModel.getPlayer1().getCol());
            fieldTableModel.getPlayer1().setRow(jTable1.getSelectedRow());
            fieldTableModel.getPlayer1().setCol(jTable1.getSelectedColumn());
       
       
        fieldTableModel.fireTableDataChanged();
        }
      
    }                                    

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {                                      
        for (int i = 0; i < 24; i++) {                                                    //Feldwertausgabe
            for (int j = 0; j < 32; j++) {
                System.out.print(fieldTableModel.getTileTable()[i][j].isSightBlock()+",");
            }
            System.out.println("");
        }
        System.out.println("");
        System.out.println(fieldTableModel.getTileTableOrigin()[0][0].toString());
        System.out.println(fieldTableModel.getTileTable()[0][0].toString());
     
     fieldTableModel.fireTableDataChanged();
    }                                     

    private void StartMouseClicked(java.awt.event.MouseEvent evt) {                                   
//        System.out.println("originalTile: "+fieldTableModel.getTileTableOrigin()[11][3].getImage());
        fieldTableModel.getPlayer1().setOccupied(true);
//        fieldTableModel.getPlayer2().setOccupied(true);
        fieldTableModel.getPlayer1().setRow(11);
        fieldTableModel.getPlayer1().setCol(10);
        
//        s2row = 10;
//        s2col = 28;
        
        fieldTableModel.getTileTable()[11][10] = fieldTableModel.getPlayer1();
//        fieldTableModel.getTileTable()[10][28] = fieldTableModel.getPlayer2();
        fieldTableModel.fireTableDataChanged();
//        System.out.println("originalTile: "+fieldTableModel.getTileTableOrigin()[11][3].getImage());
                
//        fieldTableModel.getSpieler().setOccupied(true);
//        System.out.println(fieldTableModel.getTileTable()[0][0].getImage());
//        fieldTableModel.getTileTable()[1][1].setImage(new ImageIcon("src/images/0.jpg"));       //ersetzt ein Tileobjekt im TileTable
//        fieldTableModel.setValueAt(this, WIDTH, WIDTH);                                         //ersetzt ein Objekt in der Anzeige = neuer Spielstand
//        fieldTableModel.getSpieler().setImage(new ImageIcon("src/images/spieler1.jpg"));
    }                                  

    private void movementbuttonMouseClicked(java.awt.event.MouseEvent evt) {                                            
        System.out.println("Ausgabe Koordinaten in MainFrame aus fieldTableModel: "+fieldTableModel.getPlayer1().getRow()+" "+fieldTableModel.getPlayer1().getCol());
        
        ShowMovement sm = new ShowMovement(fieldTableModel.getPlayer1().getRow(), fieldTableModel.getPlayer1().getCol(), fieldTableModel.getPlayer1().getMovementSpeed());
        sm.newNodes();
        System.out.println("kurz vor Listenausgabe");
        sm.getClosedList().remove(0);
        this.sm = sm.getClosedList();
        for (Coordinates e : sm.getClosedList() ) {
            System.out.println("x: "+e.getRow()+" y: "+e.getCol());
            fieldTableModel.getTileTable()[e.getRow()][e.getCol()].setPath(true);
            
        }
        fieldTableModel.fireTableDataChanged();
        
        
        
    }                                           

    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PAGGMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PAGGMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PAGGMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PAGGMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PAGGMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton Start;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton movementbutton;
    // End of variables declaration                   

    /**
     * @return the s1row
     */
    public int getS1row() {
        return s1row;
    }

    /**
     * @param s1row the s1row to set
     */
    public void setS1row(int s1row) {
        this.s1row = s1row;
    }

    /**
     * @return the s1col
     */
    public int getS1col() {
        return s1col;
    }

    /**
     * @param s1col the s1col to set
     */
    public void setS1col(int s1col) {
        this.s1col = s1col;
    }
    
    public FieldTableModel getFieldTableModel()
    {
        return fieldTableModel;
    }
    
//    public BufferedImage makeTranslucent(BufferedImage source, float alpha)
//            {
//               
//               Graphics2D g2d = source.createGraphics();
//               g2d.setComposite(AlphaComposite.SRC, alpha);
//               g2d.drawImage(source,0,0,null);
//               g2d.dispose();
//               return source;
//            }
    
//    public Image makeTranslucentImages(Image src) {
//            Image transImage = new Image() {
//
//                @Override
//                public int getWidth(ImageObserver observer) {
//                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//                }
//
//                @Override
//                public int getHeight(ImageObserver observer) {
//                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//                }
//
//                @Override
//                public ImageProducer getSource() {
//                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//                }
//
//                @Override
//                public Graphics getGraphics() {
//                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//                }
//
//                @Override
//                public Object getProperty(String name, ImageObserver observer) {
//                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//                }
//            };
//            int width = src.getWidth(null);
//            int height = src.getHeight(null);
//           
//                  int[] pixels = new int[width * height];
//                  PixelGrabber pg = new PixelGrabber(src, 0, 0, width, height, pixels, 0, width);
//                  try {
//                        pg.grabPixels();
//                  }
//                  catch (InterruptedException e) {
//                        System.out.println("Error grabbing pixels.");
//                  }
//
//                  for (int k = 0; k < pixels.length; k++) {
//                        int alpha = (pixels[k] >> 24) & 0xff;
//                        if (alpha != 0)
//                              pixels[k] = 0x4F000000 | (pixels[k] & 0x00FFFFFF);
//                  }
//                  transImage = Toolkit.getDefaultToolkit().createImage(new MemoryImageSource(width, height, pixels, 0, width));
//            
//            return transImage;
//      }

    class ImageCellRenderer extends JLabel implements TableCellRenderer
    {
        private JLabel lbl = new JLabel();
        private JLabel lbl2 = new JLabel("test");
        private MyLabel lbl4 = new MyLabel();
        
//        private ImageIcon image = null;
       
//        public ImageCellRenderer()
//                
//        {
////            setOpaque(true);
//                    lbl2.setOpaque(true);
//            lbl2 = new JLabel();
//            lbl2.setBackground(Color.BLUE);
//            lbl2.setForeground(Color.BLUE);
//            add(lbl2);
//        }
        
        public void fillColor(JTable t, JLabel l, boolean isSelected )
        {
            if(isSelected)
            {
                l.setBackground(t.getSelectionBackground());
                l.setForeground(t.getSelectionForeground());
            }
            else
            {
                l.setBackground(l.getBackground());
                l.setForeground(l.getForeground());
            }
        }
        
        
        
       
        public Component getTableCellRendererComponent(JTable table, Object value,
                                                       boolean isSelected,
                                                       boolean hasFocus,
                                                       int rowIndex, int colIndex)
        {
            setOpaque(true);
            setText("");
//            setIcon(fieldTableModel.getTileTable()[rowIndex][colIndex].getImage());
//            setIcon(((Tile) value).getImage());                                      //alternativ auch möglich
            ImageIcon image = new ImageIcon("src/images/blue.png");
            ImageIcon image1 = fieldTableModel.getTileTable()[rowIndex][colIndex].getImage();
              
//            ImageIcon image = new ImageIcon();
//            if( fieldTableModel.getTileTable()[rowIndex][colIndex].isPath() )
//            {
//                ImageIcon image2 = new ImageIcon("src/images/blues/"+fieldTableModel.getTileTable()[rowIndex][colIndex].getTileNum()+"b.jpg");
//                image = image2;
//            }
//            else
//            {
//                image = fieldTableModel.getTileTable()[rowIndex][colIndex].getImage();
//            }
            lbl.setIcon(image1);
            
            if( fieldTableModel.getTileTable()[rowIndex][colIndex].isPath() )
            {
//                lbl2.setOpaque(true);
//                lbl2.setBackground(Color.red);
//                lbl2.setForeground(Color.blue);
//                lbl2.setFont(lbl2.getFont().deriveFont(Font.BOLD, 48));
//
//                lbl2.setIcon(image);
//                lbl2.setText("hi");
//                
                  lbl.setIcon(new ImageIcon("src/images/blues/"+fieldTableModel.getTileTable()[rowIndex][colIndex].getTileNum()+"b.jpg"));
//                lbl.add(lbl2);
//                return lbl2;
            }
            else
            {
//                image = fieldTableModel.getTileTable()[rowIndex][colIndex].getImage();
            
            
//            if(hasFocus)
//            {
//                setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.yellow));
//            }
//            else
//            {
//                setBorder(null);
//            }
//            if(isSelected)
//            {
//                lbl.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.yellow));
//            }
//            else
//            {
//                lbl.setBorder(null);
//            }
//            lbl.setBackground(Color.blue);
//            if( fieldTableModel.getTileTable()[rowIndex][colIndex].isPath())
//            {
//                lbl.setBorder(BorderFactory.createMatteBorder(1,1,1,1,Color.BLUE.brighter()));
//            }
//            lbl.setBorder(BorderFactory.createMatteBorder(1,1,1,1,Color.BLUE.brighter()));

//            fillColor(jTable1,lbl4,isSelected);

//            return lbl;
            }
            return lbl;
        }   


    }
}
